--  This file was generated by: 
/Users/VIEWSADMIN/github/Views/SQLDataImport/fvp/make_queries_ipolate.py
-- The parameters are: 
--   path_varlist: vars_ipolate_pgy.txt
--   path_queries: interpolate_pgy.sql
--   schema_to: staging
--   table_to: priogrid_year
--   schema_ipolate: dataprep
--   table_ipolate: interpolate_pgy
--   timevar: year_id
--   groupvar: priogrid_gid
--   t_start: 1980
--   t_end: 2100

-- make_create_table_ipolate()
DROP TABLE IF EXISTS dataprep.interpolate_pgy;
CREATE TABLE dataprep.interpolate_pgy
AS SELECT 
  priogrid_gid as gid, 
  year_id as year, 
  savanna_ih,
  agri_ih,
  barren_ih,
  forest_ih,
  grass_ih,
  pasture_ih,
  shrub_ih,
  water_ih,
  urban_ih,
  bdist1,
  capdist,
  excluded
FROM staging.country_year;

CREATE INDEX ipol_idx ON dataprep.interpolate_pgy(gid, year);

-- make_queries_add_column_li()
ALTER TABLE dataprep.interpolate_pgy ADD COLUMN savanna_ih_li FLOAT;
ALTER TABLE dataprep.interpolate_pgy ADD COLUMN agri_ih_li FLOAT;
ALTER TABLE dataprep.interpolate_pgy ADD COLUMN barren_ih_li FLOAT;
ALTER TABLE dataprep.interpolate_pgy ADD COLUMN forest_ih_li FLOAT;
ALTER TABLE dataprep.interpolate_pgy ADD COLUMN grass_ih_li FLOAT;
ALTER TABLE dataprep.interpolate_pgy ADD COLUMN pasture_ih_li FLOAT;
ALTER TABLE dataprep.interpolate_pgy ADD COLUMN shrub_ih_li FLOAT;
ALTER TABLE dataprep.interpolate_pgy ADD COLUMN water_ih_li FLOAT;
ALTER TABLE dataprep.interpolate_pgy ADD COLUMN urban_ih_li FLOAT;
ALTER TABLE dataprep.interpolate_pgy ADD COLUMN bdist1_li FLOAT;
ALTER TABLE dataprep.interpolate_pgy ADD COLUMN capdist_li FLOAT;
ALTER TABLE dataprep.interpolate_pgy ADD COLUMN excluded_li FLOAT;


-- make_queries_ipolate_update()
UPDATE dataprep.interpolate_pgy SET
  savanna_ih_li = public.interpolate_priogrid_year('dataprep','interpolate_pgy','savanna_ih',gid, year),
  agri_ih_li = public.interpolate_priogrid_year('dataprep','interpolate_pgy','agri_ih',gid, year),
  barren_ih_li = public.interpolate_priogrid_year('dataprep','interpolate_pgy','barren_ih',gid, year),
  forest_ih_li = public.interpolate_priogrid_year('dataprep','interpolate_pgy','forest_ih',gid, year),
  grass_ih_li = public.interpolate_priogrid_year('dataprep','interpolate_pgy','grass_ih',gid, year),
  pasture_ih_li = public.interpolate_priogrid_year('dataprep','interpolate_pgy','pasture_ih',gid, year),
  shrub_ih_li = public.interpolate_priogrid_year('dataprep','interpolate_pgy','shrub_ih',gid, year),
  water_ih_li = public.interpolate_priogrid_year('dataprep','interpolate_pgy','water_ih',gid, year),
  urban_ih_li = public.interpolate_priogrid_year('dataprep','interpolate_pgy','urban_ih',gid, year),
  bdist1_li = public.interpolate_priogrid_year('dataprep','interpolate_pgy','bdist1',gid, year),
  capdist_li = public.interpolate_priogrid_year('dataprep','interpolate_pgy','capdist',gid, year),
  excluded_li = public.interpolate_priogrid_year('dataprep','interpolate_pgy','excluded',gid, year)
WHERE year between 1980 AND 2100;

-- make_replace_staging_li()
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS savanna_ih_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS agri_ih_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS barren_ih_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS forest_ih_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS grass_ih_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS pasture_ih_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS shrub_ih_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS water_ih_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS urban_ih_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS bdist1_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS capdist_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS excluded_li;
ALTER TABLE staging.country_year ADD COLUMN savanna_ih_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN agri_ih_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN barren_ih_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN forest_ih_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN grass_ih_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN pasture_ih_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN shrub_ih_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN water_ih_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN urban_ih_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN bdist1_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN capdist_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN excluded_li FLOAT;

-- make_update_staging_li()
UPDATE staging.priogrid_year SET
  savanna_ih_li	= c.savanna_ih_li,
  agri_ih_li	= c.agri_ih_li,
  barren_ih_li	= c.barren_ih_li,
  forest_ih_li	= c.forest_ih_li,
  grass_ih_li	= c.grass_ih_li,
  pasture_ih_li	= c.pasture_ih_li,
  shrub_ih_li	= c.shrub_ih_li,
  water_ih_li	= c.water_ih_li,
  urban_ih_li	= c.urban_ih_li,
  bdist1_li	= c.bdist1_li,
  capdist_li	= c.capdist_li,
  excluded_li	= c.excluded_li
FROM dataprep.interpolate_pgy AS c
WHERE c.gid = country_id AND c.year=year_id;
