--  This file was generated by: 
/Users/VIEWSADMIN/github/Views/SQLDataImport/fvp/make_queries_ipolate.py
-- The parameters are: 
-- path_varlist: varlist_masterdata.txt
-- path_queries: queries_interpolate.sql
-- schema_to: staging
-- table_to: country_year
-- schema_ipolate: dataprep
-- table_ipolate: cy_interp_fvp
-- timevar: year_id
-- groupvar: country_id
-- t_start: 1980
-- t_end: 2100

-- make_create_table_ipolate()
DROP TABLE IF EXISTS dataprep.cy_interp_fvp;
CREATE TABLE dataprep.cy_interp_fvp
AS SELECT 
  country_id as gid, 
  year_id as year, 
  fvp_timeindep,
  fvp_timesincepreindepwar,
  fvp_totshlowersec2024ssp2,
  fvp_totshnoedu2024ssp2,
  fvp_totshuppersec2024ssp2,
  fvp_lnpop200,
  fvp_timesinceregimechange,
  fvp_grgdpcap_oilrent,
  fvp_grgdpcap_nonoilrent,
  fvp_oilunitrent,
  fvp_oilprodcost,
  fvp_oilprod,
  fvp_bdbest_tot,
  fvp_conflict,
  fvp_dec60,
  fvp_dec70,
  fvp_dec80,
  fvp_dec90,
  fvp_durable,
  fvp_auto,
  fvp_demo,
  fvp_democracy,
  fvp_electoral,
  fvp_liberal,
  fvp_participatory,
  fvp_regime3c,
  fvp_semi,
  fvp_grgdppercapita200,
  fvp_grpop200,
  fvp_indepyear,
  fvp_lngdp200,
  fvp_lngdpcap_nonoilrent,
  fvp_lngdpcap_oilrent,
  fvp_lngdppercapita200,
  fvp_ltsc0,
  fvp_ltsc1,
  fvp_ltsc2,
  fvp_nv_agr_totl_zs,
  fvp_oilrent,
  fvp_polity2,
  fvp_population200,
  fvp_prop_discriminated,
  fvp_prop_dominant,
  fvp_prop_excluded,
  fvp_prop_irrelevant,
  fvp_prop_powerless,
  fvp_sp_dyn_imrt_in,
  fvp_sp_dyn_tfrt_in,
  ssp1_edu_sec_15_24_prop,
  ssp1_fem_male_ratio_sec,
  ssp1_non_workagepopprop,
  ssp1_pop_iiasa,
  ssp1_sec_edu_prop,
  ssp2_edu_sec_15_24_prop,
  ssp2_fem_male_ratio_sec,
  ssp2_gdp_ppp_iiasa,
  ssp2_gdp_ppp_oecd,
  ssp2_gdppercap_iiasa,
  ssp2_gdppercap_oecd,
  ssp2_non_workagepopprop,
  ssp2_pop_iiasa,
  ssp2_sec_edu_prop,
  ssp2_urban_share_iiasa,
  ssp2_compl_prim_female_20_24,
  ssp2_compl_prim_male_20_24,
  ssp2_dep_ratio,
  ssp2_f_lowsec_20_24,
  ssp2_f_uppsec_20_24,
  ssp2_incompl_prim_female_20_24,
  ssp2_incompl_prim_male_20_24,
  ssp2_m_lowsec_20_24,
  ssp2_m_uppsec_20_24,
  ssp2_non_workagepoptot,
  ssp2_tot_f_pop,
  ssp2_tot_lowsec_20_24,
  ssp2_tot_m_pop,
  ssp2_tot_noedu_20_24,
  ssp2_tot_pop,
  ssp2_tot_pop_15_19,
  ssp2_tot_pop_20_24,
  ssp2_tot_pop_above_65,
  ssp2_tot_pop_below_15,
  ssp2_tot_uppsec_20_24,
  ssp2_workagepoptot,
  ssp2_youth_bulges,
  ssp2_mmnyrsschool2024,
  ssp2_mnyrsschool2024,
  ssp2_mshlowersec2024,
  ssp2_mshnoedu2024,
  ssp2_mshuppersec2024,
  ssp2_ymhep,
  ssp2_fmnyrsschool2024,
  ssp2_fshlowersec2024,
  ssp2_fshnoedu2024,
  ssp2_fshuppersec2024,
  ssp3_edu_sec_15_24_prop,
  ssp3_fem_male_ratio_sec,
  ssp3_non_workagepopprop,
  ssp3_pop_iiasa,
  ssp3_sec_edu_prop,
  ssp4_edu_sec_15_24_prop,
  ssp4_fem_male_ratio_sec,
  ssp4_non_workagepopprop,
  ssp4_pop_iiasa,
  ssp4_sec_edu_prop,
  ssp5_edu_sec_15_24_prop,
  ssp5_fem_male_ratio_sec,
  ssp5_non_workagepopprop,
  ssp5_pop_iiasa,
  ssp5_sec_edu_prop,
  v2x_api,
  v2x_civlib,
  v2x_clphy,
  v2x_clpol,
  v2x_clpriv,
  v2x_corr,
  v2x_cspart,
  v2x_delibdem,
  v2x_edcomp_thick,
  v2x_egal,
  v2x_egaldem,
  v2x_elecreg,
  v2x_execorr,
  v2x_feduni,
  v2x_frassoc_thick,
  v2x_freexp,
  v2x_freexp_thick,
  v2x_gencl,
  v2x_gencs,
  v2x_gender,
  v2x_genpp,
  v2x_hosinter,
  v2x_jucon,
  v2x_libdem,
  v2x_liberal,
  v2x_mpi,
  v2x_partip,
  v2x_partipdem,
  v2x_polyarchy,
  v2x_pubcorr,
  v2x_suffr,
  v2x_cl_rol,
  v2x_cs_ccsi,
  v2x_dd_dd,
  v2x_dl_delib,
  v2x_eg_eqdr,
  v2x_eg_eqprotec,
  v2x_el_elecparl,
  v2x_el_elecpres,
  v2x_el_frefair,
  v2x_el_locelec,
  v2x_el_regelec,
  v2x_ex_elecreg,
  v2x_lg_elecreg,
  v2x_lg_legcon,
  v2x_lg_leginter,
  v2x_me_altinf,
  v2x_ps_party
FROM staging.country_year;

CREATE INDEX ipol_idx ON dataprep.cy_interp_fvp(gid, year);

-- make_queries_add_column_li()
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_timeindep_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_timesincepreindepwar_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_totshlowersec2024ssp2_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_totshnoedu2024ssp2_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_totshuppersec2024ssp2_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_lnpop200_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_timesinceregimechange_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_grgdpcap_oilrent_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_grgdpcap_nonoilrent_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_oilunitrent_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_oilprodcost_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_oilprod_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_bdbest_tot_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_conflict_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_dec60_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_dec70_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_dec80_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_dec90_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_durable_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_auto_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_demo_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_democracy_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_electoral_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_liberal_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_participatory_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_regime3c_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_semi_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_grgdppercapita200_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_grpop200_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_indepyear_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_lngdp200_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_lngdpcap_nonoilrent_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_lngdpcap_oilrent_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_lngdppercapita200_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_ltsc0_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_ltsc1_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_ltsc2_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_nv_agr_totl_zs_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_oilrent_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_polity2_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_population200_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_prop_discriminated_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_prop_dominant_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_prop_excluded_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_prop_irrelevant_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_prop_powerless_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_sp_dyn_imrt_in_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN fvp_sp_dyn_tfrt_in_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp1_edu_sec_15_24_prop_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp1_fem_male_ratio_sec_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp1_non_workagepopprop_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp1_pop_iiasa_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp1_sec_edu_prop_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_edu_sec_15_24_prop_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_fem_male_ratio_sec_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_gdp_ppp_iiasa_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_gdp_ppp_oecd_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_gdppercap_iiasa_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_gdppercap_oecd_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_non_workagepopprop_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_pop_iiasa_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_sec_edu_prop_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_urban_share_iiasa_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_compl_prim_female_20_24_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_compl_prim_male_20_24_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_dep_ratio_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_f_lowsec_20_24_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_f_uppsec_20_24_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_incompl_prim_female_20_24_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_incompl_prim_male_20_24_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_m_lowsec_20_24_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_m_uppsec_20_24_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_non_workagepoptot_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_tot_f_pop_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_tot_lowsec_20_24_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_tot_m_pop_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_tot_noedu_20_24_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_tot_pop_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_tot_pop_15_19_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_tot_pop_20_24_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_tot_pop_above_65_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_tot_pop_below_15_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_tot_uppsec_20_24_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_workagepoptot_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_youth_bulges_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_mmnyrsschool2024_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_mnyrsschool2024_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_mshlowersec2024_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_mshnoedu2024_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_mshuppersec2024_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_ymhep_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_fmnyrsschool2024_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_fshlowersec2024_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_fshnoedu2024_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp2_fshuppersec2024_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp3_edu_sec_15_24_prop_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp3_fem_male_ratio_sec_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp3_non_workagepopprop_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp3_pop_iiasa_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp3_sec_edu_prop_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp4_edu_sec_15_24_prop_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp4_fem_male_ratio_sec_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp4_non_workagepopprop_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp4_pop_iiasa_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp4_sec_edu_prop_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp5_edu_sec_15_24_prop_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp5_fem_male_ratio_sec_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp5_non_workagepopprop_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp5_pop_iiasa_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN ssp5_sec_edu_prop_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_api_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_civlib_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_clphy_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_clpol_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_clpriv_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_corr_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_cspart_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_delibdem_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_edcomp_thick_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_egal_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_egaldem_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_elecreg_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_execorr_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_feduni_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_frassoc_thick_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_freexp_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_freexp_thick_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_gencl_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_gencs_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_gender_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_genpp_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_hosinter_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_jucon_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_libdem_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_liberal_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_mpi_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_partip_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_partipdem_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_polyarchy_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_pubcorr_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_suffr_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_cl_rol_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_cs_ccsi_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_dd_dd_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_dl_delib_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_eg_eqdr_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_eg_eqprotec_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_el_elecparl_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_el_elecpres_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_el_frefair_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_el_locelec_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_el_regelec_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_ex_elecreg_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_lg_elecreg_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_lg_legcon_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_lg_leginter_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_me_altinf_li FLOAT;
ALTER TABLE dataprep.cy_interp_fvp ADD COLUMN v2x_ps_party_li FLOAT;


-- make_queries_ipolate_update()
UPDATE dataprep.cy_interp_fvp SET
  fvp_timeindep_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_timeindep',gid, year),
  fvp_timesincepreindepwar_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_timesincepreindepwar',gid, year),
  fvp_totshlowersec2024ssp2_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_totshlowersec2024ssp2',gid, year),
  fvp_totshnoedu2024ssp2_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_totshnoedu2024ssp2',gid, year),
  fvp_totshuppersec2024ssp2_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_totshuppersec2024ssp2',gid, year),
  fvp_lnpop200_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_lnpop200',gid, year),
  fvp_timesinceregimechange_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_timesinceregimechange',gid, year),
  fvp_grgdpcap_oilrent_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_grgdpcap_oilrent',gid, year),
  fvp_grgdpcap_nonoilrent_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_grgdpcap_nonoilrent',gid, year),
  fvp_oilunitrent_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_oilunitrent',gid, year),
  fvp_oilprodcost_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_oilprodcost',gid, year),
  fvp_oilprod_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_oilprod',gid, year),
  fvp_bdbest_tot_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_bdbest_tot',gid, year),
  fvp_conflict_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_conflict',gid, year),
  fvp_dec60_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_dec60',gid, year),
  fvp_dec70_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_dec70',gid, year),
  fvp_dec80_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_dec80',gid, year),
  fvp_dec90_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_dec90',gid, year),
  fvp_durable_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_durable',gid, year),
  fvp_auto_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_auto',gid, year),
  fvp_demo_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_demo',gid, year),
  fvp_democracy_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_democracy',gid, year),
  fvp_electoral_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_electoral',gid, year),
  fvp_liberal_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_liberal',gid, year),
  fvp_participatory_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_participatory',gid, year),
  fvp_regime3c_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_regime3c',gid, year),
  fvp_semi_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_semi',gid, year),
  fvp_grgdppercapita200_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_grgdppercapita200',gid, year),
  fvp_grpop200_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_grpop200',gid, year),
  fvp_indepyear_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_indepyear',gid, year),
  fvp_lngdp200_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_lngdp200',gid, year),
  fvp_lngdpcap_nonoilrent_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_lngdpcap_nonoilrent',gid, year),
  fvp_lngdpcap_oilrent_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_lngdpcap_oilrent',gid, year),
  fvp_lngdppercapita200_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_lngdppercapita200',gid, year),
  fvp_ltsc0_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_ltsc0',gid, year),
  fvp_ltsc1_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_ltsc1',gid, year),
  fvp_ltsc2_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_ltsc2',gid, year),
  fvp_nv_agr_totl_zs_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_nv_agr_totl_zs',gid, year),
  fvp_oilrent_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_oilrent',gid, year),
  fvp_polity2_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_polity2',gid, year),
  fvp_population200_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_population200',gid, year),
  fvp_prop_discriminated_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_prop_discriminated',gid, year),
  fvp_prop_dominant_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_prop_dominant',gid, year),
  fvp_prop_excluded_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_prop_excluded',gid, year),
  fvp_prop_irrelevant_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_prop_irrelevant',gid, year),
  fvp_prop_powerless_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_prop_powerless',gid, year),
  fvp_sp_dyn_imrt_in_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_sp_dyn_imrt_in',gid, year),
  fvp_sp_dyn_tfrt_in_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','fvp_sp_dyn_tfrt_in',gid, year),
  ssp1_edu_sec_15_24_prop_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp1_edu_sec_15_24_prop',gid, year),
  ssp1_fem_male_ratio_sec_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp1_fem_male_ratio_sec',gid, year),
  ssp1_non_workagepopprop_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp1_non_workagepopprop',gid, year),
  ssp1_pop_iiasa_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp1_pop_iiasa',gid, year),
  ssp1_sec_edu_prop_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp1_sec_edu_prop',gid, year),
  ssp2_edu_sec_15_24_prop_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_edu_sec_15_24_prop',gid, year),
  ssp2_fem_male_ratio_sec_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_fem_male_ratio_sec',gid, year),
  ssp2_gdp_ppp_iiasa_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_gdp_ppp_iiasa',gid, year),
  ssp2_gdp_ppp_oecd_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_gdp_ppp_oecd',gid, year),
  ssp2_gdppercap_iiasa_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_gdppercap_iiasa',gid, year),
  ssp2_gdppercap_oecd_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_gdppercap_oecd',gid, year),
  ssp2_non_workagepopprop_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_non_workagepopprop',gid, year),
  ssp2_pop_iiasa_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_pop_iiasa',gid, year),
  ssp2_sec_edu_prop_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_sec_edu_prop',gid, year),
  ssp2_urban_share_iiasa_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_urban_share_iiasa',gid, year),
  ssp2_compl_prim_female_20_24_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_compl_prim_female_20_24',gid, year),
  ssp2_compl_prim_male_20_24_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_compl_prim_male_20_24',gid, year),
  ssp2_dep_ratio_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_dep_ratio',gid, year),
  ssp2_f_lowsec_20_24_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_f_lowsec_20_24',gid, year),
  ssp2_f_uppsec_20_24_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_f_uppsec_20_24',gid, year),
  ssp2_incompl_prim_female_20_24_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_incompl_prim_female_20_24',gid, year),
  ssp2_incompl_prim_male_20_24_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_incompl_prim_male_20_24',gid, year),
  ssp2_m_lowsec_20_24_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_m_lowsec_20_24',gid, year),
  ssp2_m_uppsec_20_24_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_m_uppsec_20_24',gid, year),
  ssp2_non_workagepoptot_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_non_workagepoptot',gid, year),
  ssp2_tot_f_pop_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_tot_f_pop',gid, year),
  ssp2_tot_lowsec_20_24_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_tot_lowsec_20_24',gid, year),
  ssp2_tot_m_pop_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_tot_m_pop',gid, year),
  ssp2_tot_noedu_20_24_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_tot_noedu_20_24',gid, year),
  ssp2_tot_pop_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_tot_pop',gid, year),
  ssp2_tot_pop_15_19_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_tot_pop_15_19',gid, year),
  ssp2_tot_pop_20_24_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_tot_pop_20_24',gid, year),
  ssp2_tot_pop_above_65_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_tot_pop_above_65',gid, year),
  ssp2_tot_pop_below_15_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_tot_pop_below_15',gid, year),
  ssp2_tot_uppsec_20_24_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_tot_uppsec_20_24',gid, year),
  ssp2_workagepoptot_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_workagepoptot',gid, year),
  ssp2_youth_bulges_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_youth_bulges',gid, year),
  ssp2_mmnyrsschool2024_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_mmnyrsschool2024',gid, year),
  ssp2_mnyrsschool2024_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_mnyrsschool2024',gid, year),
  ssp2_mshlowersec2024_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_mshlowersec2024',gid, year),
  ssp2_mshnoedu2024_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_mshnoedu2024',gid, year),
  ssp2_mshuppersec2024_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_mshuppersec2024',gid, year),
  ssp2_ymhep_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_ymhep',gid, year),
  ssp2_fmnyrsschool2024_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_fmnyrsschool2024',gid, year),
  ssp2_fshlowersec2024_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_fshlowersec2024',gid, year),
  ssp2_fshnoedu2024_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_fshnoedu2024',gid, year),
  ssp2_fshuppersec2024_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp2_fshuppersec2024',gid, year),
  ssp3_edu_sec_15_24_prop_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp3_edu_sec_15_24_prop',gid, year),
  ssp3_fem_male_ratio_sec_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp3_fem_male_ratio_sec',gid, year),
  ssp3_non_workagepopprop_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp3_non_workagepopprop',gid, year),
  ssp3_pop_iiasa_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp3_pop_iiasa',gid, year),
  ssp3_sec_edu_prop_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp3_sec_edu_prop',gid, year),
  ssp4_edu_sec_15_24_prop_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp4_edu_sec_15_24_prop',gid, year),
  ssp4_fem_male_ratio_sec_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp4_fem_male_ratio_sec',gid, year),
  ssp4_non_workagepopprop_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp4_non_workagepopprop',gid, year),
  ssp4_pop_iiasa_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp4_pop_iiasa',gid, year),
  ssp4_sec_edu_prop_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp4_sec_edu_prop',gid, year),
  ssp5_edu_sec_15_24_prop_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp5_edu_sec_15_24_prop',gid, year),
  ssp5_fem_male_ratio_sec_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp5_fem_male_ratio_sec',gid, year),
  ssp5_non_workagepopprop_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp5_non_workagepopprop',gid, year),
  ssp5_pop_iiasa_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp5_pop_iiasa',gid, year),
  ssp5_sec_edu_prop_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','ssp5_sec_edu_prop',gid, year),
  v2x_api_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_api',gid, year),
  v2x_civlib_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_civlib',gid, year),
  v2x_clphy_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_clphy',gid, year),
  v2x_clpol_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_clpol',gid, year),
  v2x_clpriv_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_clpriv',gid, year),
  v2x_corr_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_corr',gid, year),
  v2x_cspart_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_cspart',gid, year),
  v2x_delibdem_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_delibdem',gid, year),
  v2x_edcomp_thick_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_edcomp_thick',gid, year),
  v2x_egal_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_egal',gid, year),
  v2x_egaldem_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_egaldem',gid, year),
  v2x_elecreg_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_elecreg',gid, year),
  v2x_execorr_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_execorr',gid, year),
  v2x_feduni_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_feduni',gid, year),
  v2x_frassoc_thick_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_frassoc_thick',gid, year),
  v2x_freexp_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_freexp',gid, year),
  v2x_freexp_thick_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_freexp_thick',gid, year),
  v2x_gencl_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_gencl',gid, year),
  v2x_gencs_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_gencs',gid, year),
  v2x_gender_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_gender',gid, year),
  v2x_genpp_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_genpp',gid, year),
  v2x_hosinter_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_hosinter',gid, year),
  v2x_jucon_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_jucon',gid, year),
  v2x_libdem_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_libdem',gid, year),
  v2x_liberal_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_liberal',gid, year),
  v2x_mpi_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_mpi',gid, year),
  v2x_partip_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_partip',gid, year),
  v2x_partipdem_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_partipdem',gid, year),
  v2x_polyarchy_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_polyarchy',gid, year),
  v2x_pubcorr_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_pubcorr',gid, year),
  v2x_suffr_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_suffr',gid, year),
  v2x_cl_rol_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_cl_rol',gid, year),
  v2x_cs_ccsi_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_cs_ccsi',gid, year),
  v2x_dd_dd_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_dd_dd',gid, year),
  v2x_dl_delib_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_dl_delib',gid, year),
  v2x_eg_eqdr_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_eg_eqdr',gid, year),
  v2x_eg_eqprotec_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_eg_eqprotec',gid, year),
  v2x_el_elecparl_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_el_elecparl',gid, year),
  v2x_el_elecpres_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_el_elecpres',gid, year),
  v2x_el_frefair_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_el_frefair',gid, year),
  v2x_el_locelec_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_el_locelec',gid, year),
  v2x_el_regelec_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_el_regelec',gid, year),
  v2x_ex_elecreg_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_ex_elecreg',gid, year),
  v2x_lg_elecreg_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_lg_elecreg',gid, year),
  v2x_lg_legcon_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_lg_legcon',gid, year),
  v2x_lg_leginter_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_lg_leginter',gid, year),
  v2x_me_altinf_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_me_altinf',gid, year),
  v2x_ps_party_li = public.interpolate_priogrid_year('dataprep','cy_interp_fvp','v2x_ps_party',gid, year)
WHERE year between 1980 AND 2100;

-- make_replace_staging_li()
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_timeindep_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_timesincepreindepwar_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_totshlowersec2024ssp2_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_totshnoedu2024ssp2_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_totshuppersec2024ssp2_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_lnpop200_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_timesinceregimechange_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_grgdpcap_oilrent_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_grgdpcap_nonoilrent_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_oilunitrent_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_oilprodcost_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_oilprod_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_bdbest_tot_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_conflict_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_dec60_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_dec70_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_dec80_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_dec90_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_durable_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_auto_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_demo_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_democracy_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_electoral_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_liberal_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_participatory_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_regime3c_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_semi_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_grgdppercapita200_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_grpop200_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_indepyear_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_lngdp200_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_lngdpcap_nonoilrent_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_lngdpcap_oilrent_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_lngdppercapita200_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_ltsc0_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_ltsc1_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_ltsc2_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_nv_agr_totl_zs_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_oilrent_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_polity2_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_population200_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_prop_discriminated_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_prop_dominant_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_prop_excluded_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_prop_irrelevant_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_prop_powerless_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_sp_dyn_imrt_in_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS fvp_sp_dyn_tfrt_in_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp1_edu_sec_15_24_prop_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp1_fem_male_ratio_sec_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp1_non_workagepopprop_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp1_pop_iiasa_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp1_sec_edu_prop_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_edu_sec_15_24_prop_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_fem_male_ratio_sec_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_gdp_ppp_iiasa_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_gdp_ppp_oecd_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_gdppercap_iiasa_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_gdppercap_oecd_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_non_workagepopprop_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_pop_iiasa_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_sec_edu_prop_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_urban_share_iiasa_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_compl_prim_female_20_24_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_compl_prim_male_20_24_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_dep_ratio_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_f_lowsec_20_24_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_f_uppsec_20_24_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_incompl_prim_female_20_24_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_incompl_prim_male_20_24_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_m_lowsec_20_24_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_m_uppsec_20_24_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_non_workagepoptot_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_tot_f_pop_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_tot_lowsec_20_24_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_tot_m_pop_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_tot_noedu_20_24_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_tot_pop_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_tot_pop_15_19_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_tot_pop_20_24_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_tot_pop_above_65_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_tot_pop_below_15_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_tot_uppsec_20_24_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_workagepoptot_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_youth_bulges_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_mmnyrsschool2024_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_mnyrsschool2024_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_mshlowersec2024_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_mshnoedu2024_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_mshuppersec2024_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_ymhep_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_fmnyrsschool2024_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_fshlowersec2024_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_fshnoedu2024_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp2_fshuppersec2024_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp3_edu_sec_15_24_prop_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp3_fem_male_ratio_sec_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp3_non_workagepopprop_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp3_pop_iiasa_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp3_sec_edu_prop_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp4_edu_sec_15_24_prop_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp4_fem_male_ratio_sec_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp4_non_workagepopprop_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp4_pop_iiasa_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp4_sec_edu_prop_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp5_edu_sec_15_24_prop_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp5_fem_male_ratio_sec_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp5_non_workagepopprop_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp5_pop_iiasa_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS ssp5_sec_edu_prop_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_api_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_civlib_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_clphy_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_clpol_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_clpriv_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_corr_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_cspart_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_delibdem_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_edcomp_thick_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_egal_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_egaldem_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_elecreg_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_execorr_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_feduni_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_frassoc_thick_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_freexp_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_freexp_thick_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_gencl_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_gencs_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_gender_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_genpp_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_hosinter_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_jucon_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_libdem_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_liberal_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_mpi_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_partip_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_partipdem_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_polyarchy_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_pubcorr_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_suffr_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_cl_rol_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_cs_ccsi_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_dd_dd_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_dl_delib_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_eg_eqdr_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_eg_eqprotec_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_el_elecparl_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_el_elecpres_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_el_frefair_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_el_locelec_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_el_regelec_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_ex_elecreg_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_lg_elecreg_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_lg_legcon_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_lg_leginter_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_me_altinf_li;
ALTER TABLE staging.country_year DROP COLUMN IF EXISTS v2x_ps_party_li;
ALTER TABLE staging.country_year ADD COLUMN fvp_timeindep_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_timesincepreindepwar_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_totshlowersec2024ssp2_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_totshnoedu2024ssp2_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_totshuppersec2024ssp2_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_lnpop200_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_timesinceregimechange_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_grgdpcap_oilrent_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_grgdpcap_nonoilrent_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_oilunitrent_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_oilprodcost_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_oilprod_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_bdbest_tot_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_conflict_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_dec60_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_dec70_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_dec80_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_dec90_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_durable_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_auto_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_demo_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_democracy_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_electoral_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_liberal_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_participatory_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_regime3c_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_semi_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_grgdppercapita200_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_grpop200_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_indepyear_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_lngdp200_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_lngdpcap_nonoilrent_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_lngdpcap_oilrent_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_lngdppercapita200_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_ltsc0_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_ltsc1_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_ltsc2_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_nv_agr_totl_zs_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_oilrent_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_polity2_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_population200_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_prop_discriminated_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_prop_dominant_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_prop_excluded_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_prop_irrelevant_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_prop_powerless_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_sp_dyn_imrt_in_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN fvp_sp_dyn_tfrt_in_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp1_edu_sec_15_24_prop_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp1_fem_male_ratio_sec_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp1_non_workagepopprop_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp1_pop_iiasa_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp1_sec_edu_prop_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_edu_sec_15_24_prop_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_fem_male_ratio_sec_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_gdp_ppp_iiasa_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_gdp_ppp_oecd_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_gdppercap_iiasa_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_gdppercap_oecd_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_non_workagepopprop_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_pop_iiasa_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_sec_edu_prop_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_urban_share_iiasa_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_compl_prim_female_20_24_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_compl_prim_male_20_24_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_dep_ratio_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_f_lowsec_20_24_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_f_uppsec_20_24_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_incompl_prim_female_20_24_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_incompl_prim_male_20_24_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_m_lowsec_20_24_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_m_uppsec_20_24_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_non_workagepoptot_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_tot_f_pop_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_tot_lowsec_20_24_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_tot_m_pop_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_tot_noedu_20_24_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_tot_pop_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_tot_pop_15_19_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_tot_pop_20_24_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_tot_pop_above_65_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_tot_pop_below_15_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_tot_uppsec_20_24_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_workagepoptot_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_youth_bulges_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_mmnyrsschool2024_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_mnyrsschool2024_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_mshlowersec2024_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_mshnoedu2024_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_mshuppersec2024_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_ymhep_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_fmnyrsschool2024_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_fshlowersec2024_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_fshnoedu2024_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp2_fshuppersec2024_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp3_edu_sec_15_24_prop_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp3_fem_male_ratio_sec_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp3_non_workagepopprop_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp3_pop_iiasa_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp3_sec_edu_prop_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp4_edu_sec_15_24_prop_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp4_fem_male_ratio_sec_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp4_non_workagepopprop_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp4_pop_iiasa_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp4_sec_edu_prop_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp5_edu_sec_15_24_prop_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp5_fem_male_ratio_sec_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp5_non_workagepopprop_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp5_pop_iiasa_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN ssp5_sec_edu_prop_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_api_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_civlib_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_clphy_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_clpol_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_clpriv_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_corr_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_cspart_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_delibdem_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_edcomp_thick_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_egal_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_egaldem_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_elecreg_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_execorr_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_feduni_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_frassoc_thick_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_freexp_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_freexp_thick_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_gencl_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_gencs_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_gender_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_genpp_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_hosinter_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_jucon_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_libdem_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_liberal_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_mpi_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_partip_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_partipdem_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_polyarchy_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_pubcorr_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_suffr_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_cl_rol_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_cs_ccsi_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_dd_dd_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_dl_delib_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_eg_eqdr_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_eg_eqprotec_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_el_elecparl_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_el_elecpres_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_el_frefair_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_el_locelec_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_el_regelec_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_ex_elecreg_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_lg_elecreg_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_lg_legcon_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_lg_leginter_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_me_altinf_li FLOAT;
ALTER TABLE staging.country_year ADD COLUMN v2x_ps_party_li FLOAT;

-- make_update_staging_li()
UPDATE staging.country_year SET
  fvp_timeindep_li	= c.fvp_timeindep_li,
  fvp_timesincepreindepwar_li	= c.fvp_timesincepreindepwar_li,
  fvp_totshlowersec2024ssp2_li	= c.fvp_totshlowersec2024ssp2_li,
  fvp_totshnoedu2024ssp2_li	= c.fvp_totshnoedu2024ssp2_li,
  fvp_totshuppersec2024ssp2_li	= c.fvp_totshuppersec2024ssp2_li,
  fvp_lnpop200_li	= c.fvp_lnpop200_li,
  fvp_timesinceregimechange_li	= c.fvp_timesinceregimechange_li,
  fvp_grgdpcap_oilrent_li	= c.fvp_grgdpcap_oilrent_li,
  fvp_grgdpcap_nonoilrent_li	= c.fvp_grgdpcap_nonoilrent_li,
  fvp_oilunitrent_li	= c.fvp_oilunitrent_li,
  fvp_oilprodcost_li	= c.fvp_oilprodcost_li,
  fvp_oilprod_li	= c.fvp_oilprod_li,
  fvp_bdbest_tot_li	= c.fvp_bdbest_tot_li,
  fvp_conflict_li	= c.fvp_conflict_li,
  fvp_dec60_li	= c.fvp_dec60_li,
  fvp_dec70_li	= c.fvp_dec70_li,
  fvp_dec80_li	= c.fvp_dec80_li,
  fvp_dec90_li	= c.fvp_dec90_li,
  fvp_durable_li	= c.fvp_durable_li,
  fvp_auto_li	= c.fvp_auto_li,
  fvp_demo_li	= c.fvp_demo_li,
  fvp_democracy_li	= c.fvp_democracy_li,
  fvp_electoral_li	= c.fvp_electoral_li,
  fvp_liberal_li	= c.fvp_liberal_li,
  fvp_participatory_li	= c.fvp_participatory_li,
  fvp_regime3c_li	= c.fvp_regime3c_li,
  fvp_semi_li	= c.fvp_semi_li,
  fvp_grgdppercapita200_li	= c.fvp_grgdppercapita200_li,
  fvp_grpop200_li	= c.fvp_grpop200_li,
  fvp_indepyear_li	= c.fvp_indepyear_li,
  fvp_lngdp200_li	= c.fvp_lngdp200_li,
  fvp_lngdpcap_nonoilrent_li	= c.fvp_lngdpcap_nonoilrent_li,
  fvp_lngdpcap_oilrent_li	= c.fvp_lngdpcap_oilrent_li,
  fvp_lngdppercapita200_li	= c.fvp_lngdppercapita200_li,
  fvp_ltsc0_li	= c.fvp_ltsc0_li,
  fvp_ltsc1_li	= c.fvp_ltsc1_li,
  fvp_ltsc2_li	= c.fvp_ltsc2_li,
  fvp_nv_agr_totl_zs_li	= c.fvp_nv_agr_totl_zs_li,
  fvp_oilrent_li	= c.fvp_oilrent_li,
  fvp_polity2_li	= c.fvp_polity2_li,
  fvp_population200_li	= c.fvp_population200_li,
  fvp_prop_discriminated_li	= c.fvp_prop_discriminated_li,
  fvp_prop_dominant_li	= c.fvp_prop_dominant_li,
  fvp_prop_excluded_li	= c.fvp_prop_excluded_li,
  fvp_prop_irrelevant_li	= c.fvp_prop_irrelevant_li,
  fvp_prop_powerless_li	= c.fvp_prop_powerless_li,
  fvp_sp_dyn_imrt_in_li	= c.fvp_sp_dyn_imrt_in_li,
  fvp_sp_dyn_tfrt_in_li	= c.fvp_sp_dyn_tfrt_in_li,
  ssp1_edu_sec_15_24_prop_li	= c.ssp1_edu_sec_15_24_prop_li,
  ssp1_fem_male_ratio_sec_li	= c.ssp1_fem_male_ratio_sec_li,
  ssp1_non_workagepopprop_li	= c.ssp1_non_workagepopprop_li,
  ssp1_pop_iiasa_li	= c.ssp1_pop_iiasa_li,
  ssp1_sec_edu_prop_li	= c.ssp1_sec_edu_prop_li,
  ssp2_edu_sec_15_24_prop_li	= c.ssp2_edu_sec_15_24_prop_li,
  ssp2_fem_male_ratio_sec_li	= c.ssp2_fem_male_ratio_sec_li,
  ssp2_gdp_ppp_iiasa_li	= c.ssp2_gdp_ppp_iiasa_li,
  ssp2_gdp_ppp_oecd_li	= c.ssp2_gdp_ppp_oecd_li,
  ssp2_gdppercap_iiasa_li	= c.ssp2_gdppercap_iiasa_li,
  ssp2_gdppercap_oecd_li	= c.ssp2_gdppercap_oecd_li,
  ssp2_non_workagepopprop_li	= c.ssp2_non_workagepopprop_li,
  ssp2_pop_iiasa_li	= c.ssp2_pop_iiasa_li,
  ssp2_sec_edu_prop_li	= c.ssp2_sec_edu_prop_li,
  ssp2_urban_share_iiasa_li	= c.ssp2_urban_share_iiasa_li,
  ssp2_compl_prim_female_20_24_li	= c.ssp2_compl_prim_female_20_24_li,
  ssp2_compl_prim_male_20_24_li	= c.ssp2_compl_prim_male_20_24_li,
  ssp2_dep_ratio_li	= c.ssp2_dep_ratio_li,
  ssp2_f_lowsec_20_24_li	= c.ssp2_f_lowsec_20_24_li,
  ssp2_f_uppsec_20_24_li	= c.ssp2_f_uppsec_20_24_li,
  ssp2_incompl_prim_female_20_24_li	= c.ssp2_incompl_prim_female_20_24_li,
  ssp2_incompl_prim_male_20_24_li	= c.ssp2_incompl_prim_male_20_24_li,
  ssp2_m_lowsec_20_24_li	= c.ssp2_m_lowsec_20_24_li,
  ssp2_m_uppsec_20_24_li	= c.ssp2_m_uppsec_20_24_li,
  ssp2_non_workagepoptot_li	= c.ssp2_non_workagepoptot_li,
  ssp2_tot_f_pop_li	= c.ssp2_tot_f_pop_li,
  ssp2_tot_lowsec_20_24_li	= c.ssp2_tot_lowsec_20_24_li,
  ssp2_tot_m_pop_li	= c.ssp2_tot_m_pop_li,
  ssp2_tot_noedu_20_24_li	= c.ssp2_tot_noedu_20_24_li,
  ssp2_tot_pop_li	= c.ssp2_tot_pop_li,
  ssp2_tot_pop_15_19_li	= c.ssp2_tot_pop_15_19_li,
  ssp2_tot_pop_20_24_li	= c.ssp2_tot_pop_20_24_li,
  ssp2_tot_pop_above_65_li	= c.ssp2_tot_pop_above_65_li,
  ssp2_tot_pop_below_15_li	= c.ssp2_tot_pop_below_15_li,
  ssp2_tot_uppsec_20_24_li	= c.ssp2_tot_uppsec_20_24_li,
  ssp2_workagepoptot_li	= c.ssp2_workagepoptot_li,
  ssp2_youth_bulges_li	= c.ssp2_youth_bulges_li,
  ssp2_mmnyrsschool2024_li	= c.ssp2_mmnyrsschool2024_li,
  ssp2_mnyrsschool2024_li	= c.ssp2_mnyrsschool2024_li,
  ssp2_mshlowersec2024_li	= c.ssp2_mshlowersec2024_li,
  ssp2_mshnoedu2024_li	= c.ssp2_mshnoedu2024_li,
  ssp2_mshuppersec2024_li	= c.ssp2_mshuppersec2024_li,
  ssp2_ymhep_li	= c.ssp2_ymhep_li,
  ssp2_fmnyrsschool2024_li	= c.ssp2_fmnyrsschool2024_li,
  ssp2_fshlowersec2024_li	= c.ssp2_fshlowersec2024_li,
  ssp2_fshnoedu2024_li	= c.ssp2_fshnoedu2024_li,
  ssp2_fshuppersec2024_li	= c.ssp2_fshuppersec2024_li,
  ssp3_edu_sec_15_24_prop_li	= c.ssp3_edu_sec_15_24_prop_li,
  ssp3_fem_male_ratio_sec_li	= c.ssp3_fem_male_ratio_sec_li,
  ssp3_non_workagepopprop_li	= c.ssp3_non_workagepopprop_li,
  ssp3_pop_iiasa_li	= c.ssp3_pop_iiasa_li,
  ssp3_sec_edu_prop_li	= c.ssp3_sec_edu_prop_li,
  ssp4_edu_sec_15_24_prop_li	= c.ssp4_edu_sec_15_24_prop_li,
  ssp4_fem_male_ratio_sec_li	= c.ssp4_fem_male_ratio_sec_li,
  ssp4_non_workagepopprop_li	= c.ssp4_non_workagepopprop_li,
  ssp4_pop_iiasa_li	= c.ssp4_pop_iiasa_li,
  ssp4_sec_edu_prop_li	= c.ssp4_sec_edu_prop_li,
  ssp5_edu_sec_15_24_prop_li	= c.ssp5_edu_sec_15_24_prop_li,
  ssp5_fem_male_ratio_sec_li	= c.ssp5_fem_male_ratio_sec_li,
  ssp5_non_workagepopprop_li	= c.ssp5_non_workagepopprop_li,
  ssp5_pop_iiasa_li	= c.ssp5_pop_iiasa_li,
  ssp5_sec_edu_prop_li	= c.ssp5_sec_edu_prop_li,
  v2x_api_li	= c.v2x_api_li,
  v2x_civlib_li	= c.v2x_civlib_li,
  v2x_clphy_li	= c.v2x_clphy_li,
  v2x_clpol_li	= c.v2x_clpol_li,
  v2x_clpriv_li	= c.v2x_clpriv_li,
  v2x_corr_li	= c.v2x_corr_li,
  v2x_cspart_li	= c.v2x_cspart_li,
  v2x_delibdem_li	= c.v2x_delibdem_li,
  v2x_edcomp_thick_li	= c.v2x_edcomp_thick_li,
  v2x_egal_li	= c.v2x_egal_li,
  v2x_egaldem_li	= c.v2x_egaldem_li,
  v2x_elecreg_li	= c.v2x_elecreg_li,
  v2x_execorr_li	= c.v2x_execorr_li,
  v2x_feduni_li	= c.v2x_feduni_li,
  v2x_frassoc_thick_li	= c.v2x_frassoc_thick_li,
  v2x_freexp_li	= c.v2x_freexp_li,
  v2x_freexp_thick_li	= c.v2x_freexp_thick_li,
  v2x_gencl_li	= c.v2x_gencl_li,
  v2x_gencs_li	= c.v2x_gencs_li,
  v2x_gender_li	= c.v2x_gender_li,
  v2x_genpp_li	= c.v2x_genpp_li,
  v2x_hosinter_li	= c.v2x_hosinter_li,
  v2x_jucon_li	= c.v2x_jucon_li,
  v2x_libdem_li	= c.v2x_libdem_li,
  v2x_liberal_li	= c.v2x_liberal_li,
  v2x_mpi_li	= c.v2x_mpi_li,
  v2x_partip_li	= c.v2x_partip_li,
  v2x_partipdem_li	= c.v2x_partipdem_li,
  v2x_polyarchy_li	= c.v2x_polyarchy_li,
  v2x_pubcorr_li	= c.v2x_pubcorr_li,
  v2x_suffr_li	= c.v2x_suffr_li,
  v2x_cl_rol_li	= c.v2x_cl_rol_li,
  v2x_cs_ccsi_li	= c.v2x_cs_ccsi_li,
  v2x_dd_dd_li	= c.v2x_dd_dd_li,
  v2x_dl_delib_li	= c.v2x_dl_delib_li,
  v2x_eg_eqdr_li	= c.v2x_eg_eqdr_li,
  v2x_eg_eqprotec_li	= c.v2x_eg_eqprotec_li,
  v2x_el_elecparl_li	= c.v2x_el_elecparl_li,
  v2x_el_elecpres_li	= c.v2x_el_elecpres_li,
  v2x_el_frefair_li	= c.v2x_el_frefair_li,
  v2x_el_locelec_li	= c.v2x_el_locelec_li,
  v2x_el_regelec_li	= c.v2x_el_regelec_li,
  v2x_ex_elecreg_li	= c.v2x_ex_elecreg_li,
  v2x_lg_elecreg_li	= c.v2x_lg_elecreg_li,
  v2x_lg_legcon_li	= c.v2x_lg_legcon_li,
  v2x_lg_leginter_li	= c.v2x_lg_leginter_li,
  v2x_me_altinf_li	= c.v2x_me_altinf_li,
  v2x_ps_party_li	= c.v2x_ps_party_li
FROM dataprep.cy_interp_fvp AS c
WHERE c.gid = country_id AND c.year=year_id;
