from textwrap import dedent

outcomes = ["ged_dummy_sb", "ged_dummy_ns", "ged_dummy_os", "acled_count_pr"]
lags = list(range(1,12+1))
table = "launched.imp_imp_1"
start = 109
end = 447

lines = []
varnames_lags = [] # this is to give us a copy-pasteable list of lags

header = """
-- These queries were automatically generated by SQLImputation/make_queries.py
-- It is an ugly script but it beats copy-pasting or sed
-- I should probably learn how to write sql functions
-- /Frederick
"""
lines.append(header)

for outcome in outcomes:
    for lag in lags:
        v = outcome + "_tlag"+str(lag)
        dropcol = "ALTER TABLE {t} DROP COLUMN IF EXISTS {v};".format(t=table, 
                                                                      v=v)
        lines.append(dropcol)

lines.append("")

for outcome in outcomes:
    for lag in lags:
        v = outcome + "_tlag"+str(lag)
        addcol = "ALTER TABLE {t} ADD COLUMN {v} int;".format(t=table, 
                                                              v=v)
        lines.append(addcol)

for lag in lags:
    head = """
    -- lag {l}
    UPDATE {t}
    SET""".format(t=table, l=lag)
    head = dedent(head)
    
    tail = """
    FROM {t} AS a
    WHERE
    (
        {t}.month_id=a.month_id+{l}
    AND
        {t}.pg_id = a.pg_id
    AND
        {t}.month_id BETWEEN {s} AND {e}
    );""".format(t=table, l=lag, s=start, e=end)
    tail = dedent(tail)
    
    assignments = []
    for outcome in outcomes:
        varname_l = outcome + "_tlag"+str(lag)
        varnames_lags.append(varname_l)
        varname_r = "a." + outcome
        assignment = " "*2 + varname_l + " = " + varname_r + ","
        assignments.append(assignment)
    # strip , from last assignment
    assignments[-1] = assignments[-1].strip(",")

    lines.append(head)
    for a in assignments:
        lines.append(a)
    lines.append(tail)

#for line in lines:
#    print(line)

for lag in varnames_lags:
    print(lag)

with open("queries.sql", 'w') as f:
    f.writelines("\n".join(lines))

