
-- These queries were automatically generated by SQLImputation/make_queries.py
-- It is an ugly script but it beats copy-pasting or sed
-- I should probably learn how to write sql functions
-- /Frederick

ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_sb_tlag1;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_sb_tlag2;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_sb_tlag3;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_sb_tlag4;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_sb_tlag5;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_sb_tlag6;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_sb_tlag7;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_sb_tlag8;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_sb_tlag9;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_sb_tlag10;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_sb_tlag11;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_sb_tlag12;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_ns_tlag1;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_ns_tlag2;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_ns_tlag3;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_ns_tlag4;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_ns_tlag5;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_ns_tlag6;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_ns_tlag7;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_ns_tlag8;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_ns_tlag9;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_ns_tlag10;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_ns_tlag11;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_ns_tlag12;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_os_tlag1;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_os_tlag2;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_os_tlag3;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_os_tlag4;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_os_tlag5;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_os_tlag6;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_os_tlag7;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_os_tlag8;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_os_tlag9;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_os_tlag10;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_os_tlag11;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS ged_dummy_os_tlag12;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS acled_count_pr_tlag1;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS acled_count_pr_tlag2;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS acled_count_pr_tlag3;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS acled_count_pr_tlag4;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS acled_count_pr_tlag5;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS acled_count_pr_tlag6;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS acled_count_pr_tlag7;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS acled_count_pr_tlag8;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS acled_count_pr_tlag9;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS acled_count_pr_tlag10;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS acled_count_pr_tlag11;
ALTER TABLE launched.imp_imp_1 DROP COLUMN IF EXISTS acled_count_pr_tlag12;

ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_sb_tlag1 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_sb_tlag2 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_sb_tlag3 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_sb_tlag4 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_sb_tlag5 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_sb_tlag6 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_sb_tlag7 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_sb_tlag8 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_sb_tlag9 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_sb_tlag10 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_sb_tlag11 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_sb_tlag12 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_ns_tlag1 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_ns_tlag2 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_ns_tlag3 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_ns_tlag4 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_ns_tlag5 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_ns_tlag6 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_ns_tlag7 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_ns_tlag8 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_ns_tlag9 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_ns_tlag10 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_ns_tlag11 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_ns_tlag12 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_os_tlag1 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_os_tlag2 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_os_tlag3 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_os_tlag4 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_os_tlag5 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_os_tlag6 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_os_tlag7 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_os_tlag8 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_os_tlag9 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_os_tlag10 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_os_tlag11 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN ged_dummy_os_tlag12 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN acled_count_pr_tlag1 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN acled_count_pr_tlag2 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN acled_count_pr_tlag3 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN acled_count_pr_tlag4 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN acled_count_pr_tlag5 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN acled_count_pr_tlag6 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN acled_count_pr_tlag7 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN acled_count_pr_tlag8 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN acled_count_pr_tlag9 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN acled_count_pr_tlag10 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN acled_count_pr_tlag11 int;
ALTER TABLE launched.imp_imp_1 ADD COLUMN acled_count_pr_tlag12 int;

-- lag 1
UPDATE launched.imp_imp_1
SET
  ged_dummy_sb_tlag1 = a.ged_dummy_sb,
  ged_dummy_ns_tlag1 = a.ged_dummy_ns,
  ged_dummy_os_tlag1 = a.ged_dummy_os,
  acled_count_pr_tlag1 = a.acled_count_pr

FROM launched.imp_imp_1 AS a
WHERE
(
    launched.imp_imp_1.month_id=a.month_id+1
AND
    launched.imp_imp_1.pg_id = a.pg_id
AND
    launched.imp_imp_1.month_id BETWEEN 109 AND 447
);

-- lag 2
UPDATE launched.imp_imp_1
SET
  ged_dummy_sb_tlag2 = a.ged_dummy_sb,
  ged_dummy_ns_tlag2 = a.ged_dummy_ns,
  ged_dummy_os_tlag2 = a.ged_dummy_os,
  acled_count_pr_tlag2 = a.acled_count_pr

FROM launched.imp_imp_1 AS a
WHERE
(
    launched.imp_imp_1.month_id=a.month_id+2
AND
    launched.imp_imp_1.pg_id = a.pg_id
AND
    launched.imp_imp_1.month_id BETWEEN 109 AND 447
);

-- lag 3
UPDATE launched.imp_imp_1
SET
  ged_dummy_sb_tlag3 = a.ged_dummy_sb,
  ged_dummy_ns_tlag3 = a.ged_dummy_ns,
  ged_dummy_os_tlag3 = a.ged_dummy_os,
  acled_count_pr_tlag3 = a.acled_count_pr

FROM launched.imp_imp_1 AS a
WHERE
(
    launched.imp_imp_1.month_id=a.month_id+3
AND
    launched.imp_imp_1.pg_id = a.pg_id
AND
    launched.imp_imp_1.month_id BETWEEN 109 AND 447
);

-- lag 4
UPDATE launched.imp_imp_1
SET
  ged_dummy_sb_tlag4 = a.ged_dummy_sb,
  ged_dummy_ns_tlag4 = a.ged_dummy_ns,
  ged_dummy_os_tlag4 = a.ged_dummy_os,
  acled_count_pr_tlag4 = a.acled_count_pr

FROM launched.imp_imp_1 AS a
WHERE
(
    launched.imp_imp_1.month_id=a.month_id+4
AND
    launched.imp_imp_1.pg_id = a.pg_id
AND
    launched.imp_imp_1.month_id BETWEEN 109 AND 447
);

-- lag 5
UPDATE launched.imp_imp_1
SET
  ged_dummy_sb_tlag5 = a.ged_dummy_sb,
  ged_dummy_ns_tlag5 = a.ged_dummy_ns,
  ged_dummy_os_tlag5 = a.ged_dummy_os,
  acled_count_pr_tlag5 = a.acled_count_pr

FROM launched.imp_imp_1 AS a
WHERE
(
    launched.imp_imp_1.month_id=a.month_id+5
AND
    launched.imp_imp_1.pg_id = a.pg_id
AND
    launched.imp_imp_1.month_id BETWEEN 109 AND 447
);

-- lag 6
UPDATE launched.imp_imp_1
SET
  ged_dummy_sb_tlag6 = a.ged_dummy_sb,
  ged_dummy_ns_tlag6 = a.ged_dummy_ns,
  ged_dummy_os_tlag6 = a.ged_dummy_os,
  acled_count_pr_tlag6 = a.acled_count_pr

FROM launched.imp_imp_1 AS a
WHERE
(
    launched.imp_imp_1.month_id=a.month_id+6
AND
    launched.imp_imp_1.pg_id = a.pg_id
AND
    launched.imp_imp_1.month_id BETWEEN 109 AND 447
);

-- lag 7
UPDATE launched.imp_imp_1
SET
  ged_dummy_sb_tlag7 = a.ged_dummy_sb,
  ged_dummy_ns_tlag7 = a.ged_dummy_ns,
  ged_dummy_os_tlag7 = a.ged_dummy_os,
  acled_count_pr_tlag7 = a.acled_count_pr

FROM launched.imp_imp_1 AS a
WHERE
(
    launched.imp_imp_1.month_id=a.month_id+7
AND
    launched.imp_imp_1.pg_id = a.pg_id
AND
    launched.imp_imp_1.month_id BETWEEN 109 AND 447
);

-- lag 8
UPDATE launched.imp_imp_1
SET
  ged_dummy_sb_tlag8 = a.ged_dummy_sb,
  ged_dummy_ns_tlag8 = a.ged_dummy_ns,
  ged_dummy_os_tlag8 = a.ged_dummy_os,
  acled_count_pr_tlag8 = a.acled_count_pr

FROM launched.imp_imp_1 AS a
WHERE
(
    launched.imp_imp_1.month_id=a.month_id+8
AND
    launched.imp_imp_1.pg_id = a.pg_id
AND
    launched.imp_imp_1.month_id BETWEEN 109 AND 447
);

-- lag 9
UPDATE launched.imp_imp_1
SET
  ged_dummy_sb_tlag9 = a.ged_dummy_sb,
  ged_dummy_ns_tlag9 = a.ged_dummy_ns,
  ged_dummy_os_tlag9 = a.ged_dummy_os,
  acled_count_pr_tlag9 = a.acled_count_pr

FROM launched.imp_imp_1 AS a
WHERE
(
    launched.imp_imp_1.month_id=a.month_id+9
AND
    launched.imp_imp_1.pg_id = a.pg_id
AND
    launched.imp_imp_1.month_id BETWEEN 109 AND 447
);

-- lag 10
UPDATE launched.imp_imp_1
SET
  ged_dummy_sb_tlag10 = a.ged_dummy_sb,
  ged_dummy_ns_tlag10 = a.ged_dummy_ns,
  ged_dummy_os_tlag10 = a.ged_dummy_os,
  acled_count_pr_tlag10 = a.acled_count_pr

FROM launched.imp_imp_1 AS a
WHERE
(
    launched.imp_imp_1.month_id=a.month_id+10
AND
    launched.imp_imp_1.pg_id = a.pg_id
AND
    launched.imp_imp_1.month_id BETWEEN 109 AND 447
);

-- lag 11
UPDATE launched.imp_imp_1
SET
  ged_dummy_sb_tlag11 = a.ged_dummy_sb,
  ged_dummy_ns_tlag11 = a.ged_dummy_ns,
  ged_dummy_os_tlag11 = a.ged_dummy_os,
  acled_count_pr_tlag11 = a.acled_count_pr

FROM launched.imp_imp_1 AS a
WHERE
(
    launched.imp_imp_1.month_id=a.month_id+11
AND
    launched.imp_imp_1.pg_id = a.pg_id
AND
    launched.imp_imp_1.month_id BETWEEN 109 AND 447
);

-- lag 12
UPDATE launched.imp_imp_1
SET
  ged_dummy_sb_tlag12 = a.ged_dummy_sb,
  ged_dummy_ns_tlag12 = a.ged_dummy_ns,
  ged_dummy_os_tlag12 = a.ged_dummy_os,
  acled_count_pr_tlag12 = a.acled_count_pr

FROM launched.imp_imp_1 AS a
WHERE
(
    launched.imp_imp_1.month_id=a.month_id+12
AND
    launched.imp_imp_1.pg_id = a.pg_id
AND
    launched.imp_imp_1.month_id BETWEEN 109 AND 447
);