-- This file was generated by SQLGenerators/select_imp_pgm_cm.py
-- These queries join the PGM and CM level imputed right hand side
-- variables with the geoimputed GED events and unimputed ACLED.
-- Output is at the PGM level.


SELECT
  pgm.pg_id,
  pgm.month_id,
  pgm.country_id,
  geoimp.ged_sb_dummy_3 AS ged_dummy_sb,
  geoimp.ged_ns_dummy_3 AS ged_dummy_ns,
  geoimp.ged_os_dummy_3 AS ged_dummy_os,
  public.to_dummy(CAST(preflight_pgm.acled_count_pr AS INT)) AS acled_dummy_pr,
  preflight_pgm.ged_minor_sb,
  preflight_pgm.ged_medium_sb,
  preflight_pgm.ged_major_sb,
  preflight_pgm.ged_minor_ns,
  preflight_pgm.ged_medium_ns,
  preflight_pgm.ged_major_ns,
  preflight_pgm.ged_minor_os,
  preflight_pgm.ged_medium_os,
  preflight_pgm.ged_major_os,
  pgm.bdist3,
  pgm.ttime_mean,
  pgm.capdist_li,
  pgm.pop_li_gpw_sum,
  pgm.dist_diamsec_s_wgs,
  pgm.dist_petroleum_s_wgs,
  pgm.gcp_li_mer,
  pgm.imr_mean,
  pgm.mountains_mean,
  pgm.urban_ih_li,
  public.to_dummy(CAST(pgm.excluded_li AS INT)) AS excluded_dummy_li,
  pgm.agri_ih_li,
  pgm.barren_ih_li,
  pgm.forest_ih_li,
  pgm.savanna_ih_li,
  pgm.shrub_ih_li,
  pgm.pasture_ih_li,
  cm.fvp_lngdpcap_nonoilrent,
  cm.fvp_lngdpcap_oilrent,
  cm.fvp_population200,
  cm.fvp_grgdpcap_oilrent,
  cm.fvp_grgdpcap_nonoilrent,
  cm.fvp_timeindep,
  cm.fvp_timesincepreindepwar,
  cm.fvp_timesinceregimechange,
  cm.fvp_demo,
  cm.fvp_semi,
  cm.ssp2_edu_sec_15_24_prop,
  cm.fvp_prop_excluded,
  cm.ssp2_urban_share_iiasa
FROM
  launched.pgmimp3bnd as pgm
LEFT JOIN
  launched.cm_imp_3 as cm
  ON
    pgm.country_id=cm.country_id
  AND
    pgm.month_id=cm.month_id
LEFT JOIN
    left_imputation.pgm AS geoimp
  ON
    pgm.pg_id=geoimp.priogrid_gid
  AND
    pgm.month_id=geoimp.month_id
LEFT JOIN
    preflight.flight_pgm AS preflight_pgm
  ON
    preflight_pgm.pg_id=pgm.pg_id
  AND
    preflight_pgm.month_id=pgm.month_id;