# EBMA
# Simple Average
# CL

import json

ensembles_pgm = {
    "average_select_OUTCOME": [
        "ds_pgm_canon_nocm_RUNTYPE_test_OUTCOME",
        "ds_pgm_canon_wcm_RUNTYPE_test_OUTCOME",
        "ds_pgm_acled_wcm_RUNTYPE_test_OUTCOME",
        "osa_pgm_acled_nocm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_acled_wcm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_canon_nocm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_canon_nocm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_canon_wcm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "cl_ds_pgm_canon_nocm_RUNTYPE_test_OUTCOME",
        "cl_ds_pgm_acled_nocm_RUNTYPE_test_OUTCOME",
        "cl_osa_pgm_canon_nocm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "cl_osa_pgm_acled_nocm_RUNTYPE_test_rf_downsampled_OUTCOME"
    ],
    "average_wcm_OUTCOME": [
        "ds_pgm_canon_nocm_RUNTYPE_test_OUTCOME",
        "ds_pgm_canon_wcm_RUNTYPE_test_OUTCOME",
        "ds_pgm_acled_nocm_RUNTYPE_test_OUTCOME",
        "ds_pgm_acled_wcm_RUNTYPE_test_OUTCOME",
        "osa_pgm_acled_nocm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_acled_nocm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_acled_wcm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_acled_wcm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_canon_nocm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_canon_nocm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_canon_wcm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_canon_wcm_RUNTYPE_test_rf_downsampled_OUTCOME"
    ],
    "average_all_OUTCOME": [
        "ds_pgm_canon_nocm_RUNTYPE_test_OUTCOME",
        "ds_pgm_canon_wcm_RUNTYPE_test_OUTCOME",
        "ds_pgm_acled_nocm_RUNTYPE_test_OUTCOME",
        "ds_pgm_acled_wcm_RUNTYPE_test_OUTCOME",
        "osa_pgm_acled_nocm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_acled_nocm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_acled_wcm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_acled_wcm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_canon_nocm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_canon_nocm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_canon_wcm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_canon_wcm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "cl_ds_pgm_canon_nocm_RUNTYPE_test_OUTCOME",
        "cl_ds_pgm_acled_nocm_RUNTYPE_test_OUTCOME",
        "cl_osa_pgm_canon_nocm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "cl_osa_pgm_acled_nocm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "cl_osa_pgm_canon_nocm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "cl_osa_pgm_acled_nocm_RUNTYPE_test_rf_downsampled_OUTCOME"
    ],
    "average_allwthematic_OUTCOME": [
        "cl_ds_pgm_canon_nocm_RUNTYPE_test_OUTCOME",
        "cl_osa_pgm_canon_nocm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "cl_osa_pgm_canon_nocm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "ds_pgm_acled_cm_RUNTYPE_test_OUTCOME",
        "ds_pgm_acled_histonly_RUNTYPE_test_OUTCOME",
        "ds_pgm_acled_mean_RUNTYPE_test_OUTCOME",
        "ds_pgm_acled_nat_RUNTYPE_test_OUTCOME",
        "ds_pgm_acled_nocm_RUNTYPE_test_OUTCOME",
        "ds_pgm_acled_protest_RUNTYPE_test_OUTCOME",
        "ds_pgm_acled_soc_RUNTYPE_test_OUTCOME",
        "ds_pgm_canon_nocm_RUNTYPE_test_OUTCOME",
        "ds_pgm_canon_wcm_RUNTYPE_test_OUTCOME",
        "osa_pgm_acled_cm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_acled_cm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_acled_histonly_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_acled_histonly_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_acled_mean_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_acled_mean_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_acled_nat_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_acled_nat_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_acled_nocm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_acled_nocm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_acled_protest_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_acled_protest_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_acled_soc_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_acled_soc_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_canon_nocm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_canon_nocm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_canon_wcm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_canon_wcm_RUNTYPE_test_rf_downsampled_OUTCOME",
    ],
    "average_cl_OUTCOME": [
        "ds_pgm_canon_nocm_RUNTYPE_test_OUTCOME",
        "ds_pgm_acled_nocm_RUNTYPE_test_OUTCOME",
        "osa_pgm_acled_nocm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_acled_nocm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_canon_nocm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_canon_nocm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "cl_ds_pgm_canon_nocm_RUNTYPE_test_OUTCOME",
        "cl_ds_pgm_acled_nocm_RUNTYPE_test_OUTCOME",
        "cl_osa_pgm_canon_nocm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "cl_osa_pgm_acled_nocm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "cl_osa_pgm_canon_nocm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "cl_osa_pgm_acled_nocm_RUNTYPE_test_rf_downsampled_OUTCOME"
    ],
    "average_nocm_OUTCOME": [
        "ds_pgm_canon_nocm_RUNTYPE_test_OUTCOME",
        "ds_pgm_acled_nocm_RUNTYPE_test_OUTCOME",
        "osa_pgm_acled_nocm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_acled_nocm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_canon_nocm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_canon_nocm_RUNTYPE_test_rf_downsampled_OUTCOME"
    ],
    "average_selectwthematic_OUTCOME": [
        "ds_pgm_canon_nocm_RUNTYPE_test_OUTCOME",
        "ds_pgm_canon_wcm_RUNTYPE_test_OUTCOME",
        "osa_pgm_acled_nocm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_canon_nocm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_canon_nocm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_canon_wcm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "cl_ds_pgm_canon_nocm_RUNTYPE_test_OUTCOME",
        "cl_ds_pgm_acled_nocm_RUNTYPE_test_OUTCOME",
        "cl_osa_pgm_canon_nocm_RUNTYPE_test_logit_fullsample_OUTCOME",
        "cl_osa_pgm_acled_nocm_RUNTYPE_test_rf_downsampled_OUTCOME",
        "ds_pgm_acled_soc_RUNTYPE_test_OUTCOME",
        "ds_pgm_acled_nat_RUNTYPE_test_OUTCOME",
        "ds_pgm_acled_mean_RUNTYPE_test_OUTCOME",
        "ds_pgm_acled_histonly_RUNTYPE_test_OUTCOME",
        "osa_pgm_acled_soc_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_acled_nat_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_acled_mean_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_acled_histonly_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_acled_soc_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_acled_nat_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_acled_mean_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_acled_histonly_RUNTYPE_test_logit_fullsample_OUTCOME",
    ],
    "average_thematiconly_OUTCOME": [
        "ds_pgm_acled_soc_RUNTYPE_test_OUTCOME",
        "ds_pgm_acled_nat_RUNTYPE_test_OUTCOME",
        "ds_pgm_acled_mean_RUNTYPE_test_OUTCOME",
        "ds_pgm_acled_histonly_RUNTYPE_test_OUTCOME",
        "osa_pgm_acled_soc_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_acled_nat_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_acled_mean_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_acled_histonly_RUNTYPE_test_rf_downsampled_OUTCOME",
        "osa_pgm_acled_soc_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_acled_nat_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_acled_mean_RUNTYPE_test_logit_fullsample_OUTCOME",
        "osa_pgm_acled_histonly_RUNTYPE_test_logit_fullsample_OUTCOME",
    ]
}

ensembles_cm = {

        "average_base_OUTCOME": [
            "osa_cm_acled_base_RUNTYPE_test_logit_fullsample_OUTCOME",
            "osa_cm_acled_base_RUNTYPE_test_rf_downsampled_OUTCOME",
            "osa_cm_canon_base_RUNTYPE_test_logit_fullsample_OUTCOME",
            "osa_cm_canon_base_RUNTYPE_test_rf_downsampled_OUTCOME",
            "ds_cm_acled_base_RUNTYPE_test_OUTCOME",
            "ds_cm_canon_base_RUNTYPE_test_OUTCOME"
        ],
        "average_thematic_OUTCOME": [
            "osa_cm_canon_mean_RUNTYPE_test_logit_fullsample_OUTCOME",
            "osa_cm_canon_demog_RUNTYPE_test_logit_fullsample_OUTCOME",
            "osa_cm_canon_eco_RUNTYPE_test_logit_fullsample_OUTCOME",
            "osa_cm_canon_hist_RUNTYPE_test_logit_fullsample_OUTCOME",
            "osa_cm_canon_inst_RUNTYPE_test_logit_fullsample_OUTCOME",
            "osa_cm_canon_mean_RUNTYPE_test_rf_downsampled_OUTCOME",
            "osa_cm_canon_demog_RUNTYPE_test_rf_downsampled_OUTCOME",
            "osa_cm_canon_eco_RUNTYPE_test_rf_downsampled_OUTCOME",
            "osa_cm_canon_hist_RUNTYPE_test_rf_downsampled_OUTCOME",
            "osa_cm_canon_inst_RUNTYPE_test_rf_downsampled_OUTCOME",
            "ds_cm_canon_mean_RUNTYPE_test_OUTCOME",
            "ds_cm_canon_demog_RUNTYPE_test_OUTCOME",
            "ds_cm_canon_eco_RUNTYPE_test_OUTCOME",
            "ds_cm_canon_hist_RUNTYPE_test_OUTCOME",
            "ds_cm_canon_inst_RUNTYPE_test_OUTCOME"
        ],
        "average_basewthematic_OUTCOME": [
            "ds_cm_acled_base_RUNTYPE_test_OUTCOME",
            "ds_cm_canon_base_RUNTYPE_test_OUTCOME",
            "ds_cm_canon_mean_RUNTYPE_test_OUTCOME",
            "ds_cm_canon_demog_RUNTYPE_test_OUTCOME",
            "ds_cm_canon_eco_RUNTYPE_test_OUTCOME",
            "ds_cm_canon_hist_RUNTYPE_test_OUTCOME",
            "ds_cm_canon_inst_RUNTYPE_test_OUTCOME",
            "ds_cm_canon_protest_RUNTYPE_test_OUTCOME",
            "osa_cm_acled_base_RUNTYPE_test_logit_fullsample_OUTCOME",
            "osa_cm_canon_base_RUNTYPE_test_logit_fullsample_OUTCOME",
            "osa_cm_canon_mean_RUNTYPE_test_logit_fullsample_OUTCOME",
            "osa_cm_canon_demog_RUNTYPE_test_logit_fullsample_OUTCOME",
            "osa_cm_canon_eco_RUNTYPE_test_logit_fullsample_OUTCOME",
            "osa_cm_canon_hist_RUNTYPE_test_logit_fullsample_OUTCOME",
            "osa_cm_canon_inst_RUNTYPE_test_logit_fullsample_OUTCOME",
            "osa_cm_canon_protest_RUNTYPE_test_logit_fullsample_OUTCOME",
            "osa_cm_canon_base_RUNTYPE_test_rf_downsampled_OUTCOME",
            "osa_cm_acled_base_RUNTYPE_test_rf_downsampled_OUTCOME",
            "osa_cm_canon_mean_RUNTYPE_test_rf_downsampled_OUTCOME",
            "osa_cm_canon_demog_RUNTYPE_test_rf_downsampled_OUTCOME",
            "osa_cm_canon_eco_RUNTYPE_test_rf_downsampled_OUTCOME",
            "osa_cm_canon_hist_RUNTYPE_test_rf_downsampled_OUTCOME",
            "osa_cm_canon_inst_RUNTYPE_test_rf_downsampled_OUTCOME",
            "osa_cm_canon_protest_RUNTYPE_test_rf_downsampled_OUTCOME",
        ]
}


with open("ensembles_pgm.json", 'w') as f:
    f.write(json.dumps(ensembles_pgm, indent=4))
with open("ensembles_cm.json", 'w') as f:
    f.write(json.dumps(ensembles_cm, indent=4))
